# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
