# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='steps',
            field=models.ManyToManyField(blank=True, null=True, to='tutorials.Step', verbose_name='steps'),
        ),
    ]
