# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20161203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='steps',
            field=models.ManyToManyField(blank=True, to='tutorials.Step', verbose_name='steps'),
        ),
    ]
